fieldLen: 16
fieldWid: 8
inflationMeters: 0.1
triggerAheadMeters: 1.53734904123139
triggerWidthMeters: 0.507284568296468
corridorSamples: 3
occHigh: 0.523881531735643
occLow: 0.05
lateralMeters: 0.5
lateralMaxMeters: 2.5
minLateralMeters: 0.214363232693585
forwardMeters: 1.95808647299567
forwardMaxMeters: 2.51443501114399
holdMinSeconds: 0.2
recalcSeconds: 0.35
subgoalMaxSeconds: 0.93191461193158
minHeadingErrToTriggerDeg: 14.6045195045416
releaseAheadMeters: 1.97782296206837
angleCostWeight: 0.25645325869314
curvatureWeight: 0.249868932093618
wallPenaltyGain: 0.253775937873585
occCostGain: 0.613101020258334
sideSwitchPenalty: 1.19379632022988
headingDeadbandDeg: 0
minProgressMeters: 0.08
probeOccLegStep: 0.488907290998475
sideBiasProbeAngleDeg: 25
sideStickSeconds: 0.207454294511613
subgoalSlewRateMps: 4.41113111664602
subgoalJitterMeters: 0.0989231904520809
arcAngleDeg: 35
arcRMin: 0.3
arcRMax: 1
arcRadialSteps: 4
arcAngularStepsPerSide: 2
relatchImproveFrac: 0.197445291613057
zzzMaxYawDeltaDeg: 40
zzzPenalty: 0.324198166069881
vibWindowS: 0.3
vibMinDisp: 0.263194169609729
vibMaxDirFlips: 10
escapeForward: 2.04675164876079
escapeLateral: 2
escapeHoldS: 0.2
escapeOccBoost: 0.484785600009939
progressCostWeight: 0.351215054957617
minForwardProgressMeters: 0.1
nearGoalDistMeters: 1
nearGoalForwardScale: 0.3
nearGoalLateralScale: 1
stuckMinForwardProgress: 0.389952718337844
stuckOccMin: 0.605132291111996
stuckLookbackFrac: 0.572708244261724
sideSwitchStuckPenaltyScale: 0.922021752824538
pinnedOccMin: 0.618540862342867
pinnedMinTimeSeconds: 1.5
pinnedMaxTimeSeconds: 4.67867679800594
pinnedCooldownSeconds: 1.46422272290536
cornerWallThresh: 6
cornerEscapeLatBoost: 2.90325709431144
cornerEscapeFwdBoost: 1.53506805841441
cornerEscapeBlend: 0.63059810091707
cornerRewardGain: 0.970779179948118
